package commands

// PackageManagerUpdateCommands maps package managers to tools and their update commands
var PackageManagerUpdateCommands = LifecycleCommandsType{
	"Homebrew": {
		"git":        "brew upgrade git",
		"docker":     "brew upgrade docker",
		"lazygit":    "brew upgrade lazygit",
		"lazydocker": "brew upgrade lazydocker",
		"htop":       "brew upgrade htop",
		"nvim":       "brew upgrade nvim",
		"zsh":        "brew upgrade zsh",
		"tmux":       "brew upgrade tmux",
		"fzf":        "brew upgrade fzf",
		"ripgrep":    "brew upgrade ripgrep",
		"fd":         "brew upgrade fd",
		"bat":        "brew upgrade bat",
		"jq":         "brew upgrade jq",
	},
	"Curl": {
		"git":        "curl -fsSL https://git-scm.com/download/linux -o /tmp/git-installer.sh && chmod +x /tmp/git-installer.sh && /tmp/git-installer.sh",
		"docker":     "curl -fsSL https://get.docker.com -o /tmp/get-docker.sh && chmod +x /tmp/get-docker.sh && sh /tmp/get-docker.sh",
		"lazygit":    "curl -fsSL https://raw.githubusercontent.com/jesseduffield/lazygit/master/pkg/installer/install.sh -o /tmp/lazygit-install.sh && chmod +x /tmp/lazygit-install.sh && /tmp/lazygit-install.sh",
		"lazydocker": "curl -fsSL https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install.sh -o /tmp/lazydocker-install.sh && chmod +x /tmp/lazydocker-install.sh && /tmp/lazydocker-install.sh",
		"htop":       "curl -fsSL https://github.com/htop-dev/htop/releases/download/3.3.0/htop-3.3.0.tar.xz -o /tmp/htop.tar.xz && cd /tmp && tar -xf htop.tar.xz && cd htop-3.3.0 && ./configure && make && sudo make install",
		"nvim":       "curl -fsSL https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz -o /tmp/nvim.tar.gz && cd /tmp && tar -xzf nvim.tar.gz && sudo cp -r nvim-linux64/* /usr/local/",
		"zsh":        "curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -o /tmp/zsh-install.sh && chmod +x /tmp/zsh-install.sh && sh /tmp/zsh-install.sh",
		"tmux":       "curl -fsSL https://github.com/tmux/tmux/releases/latest/download/tmux-3.4.tar.gz -o /tmp/tmux.tar.gz && cd /tmp && tar -xzf tmux.tar.gz && cd tmux-3.4 && ./configure && make && sudo make install",
		"fzf":        "curl -fsSL https://raw.githubusercontent.com/junegunn/fzf/master/install -o /tmp/fzf-install.sh && chmod +x /tmp/fzf-install.sh && /tmp/fzf-install.sh",
		"ripgrep":    "curl -fsSL https://github.com/BurntSushi/ripgrep/releases/latest/download/ripgrep_$(uname -m)-unknown-linux-gnu.tar.gz -o /tmp/rg.tar.gz && cd /tmp && tar -xzf rg.tar.gz && sudo cp ripgrep*/rg /usr/local/bin/",
		"fd":         "curl -fsSL https://github.com/sharkdp/fd/releases/latest/download/fd-$(uname -m)-unknown-linux-gnu.tar.gz -o /tmp/fd.tar.gz && cd /tmp && tar -xzf fd.tar.gz && sudo cp fd-*/fd /usr/local/bin/",
		"bat":        "curl -fsSL https://github.com/sharkdp/bat/releases/latest/download/bat-$(uname -m)-unknown-linux-gnu.tar.gz -o /tmp/bat.tar.gz && cd /tmp && tar -xzf bat.tar.gz && sudo cp bat-*/bat /usr/local/bin/",
		"jq":         "curl -fsSL https://github.com/stedolan/jq/releases/latest/download/jq-linux64 -o /tmp/jq && chmod +x /tmp/jq && sudo mv /tmp/jq /usr/local/bin/",
	},
	"APT": {
		"git":        "apt-get update && apt-get upgrade -y git",
		"docker":     "apt-get update && apt-get upgrade -y docker.io",
		"lazygit":    "apt-get update && apt-get upgrade -y lazygit",
		"lazydocker": "apt-get update && apt-get upgrade -y lazydocker",
		"htop":       "apt-get update && apt-get upgrade -y htop",
		"nvim":       "apt-get update && apt-get upgrade -y neovim",
		"zsh":        "apt-get update && apt-get upgrade -y zsh",
		"tmux":       "apt-get update && apt-get upgrade -y tmux",
		"fzf":        "apt-get update && apt-get upgrade -y fzf",
		"ripgrep":    "apt-get update && apt-get upgrade -y ripgrep",
		"fd":         "apt-get update && apt-get upgrade -y fd-find",
		"bat":        "apt-get update && apt-get upgrade -y bat",
		"jq":         "apt-get update && apt-get upgrade -y jq",
	},
	"YUM": {
		"git":        "yum update -y git",
		"docker":     "yum update -y docker",
		"lazygit":    "yum update -y lazygit",
		"lazydocker": "yum update -y lazydocker",
		"htop":       "yum update -y htop",
		"nvim":       "yum update -y neovim",
		"zsh":        "yum update -y zsh",
		"tmux":       "yum update -y tmux",
		"fzf":        "yum update -y fzf",
		"ripgrep":    "yum update -y ripgrep",
		"fd":         "yum update -y fd-find",
		"bat":        "yum update -y bat",
		"jq":         "yum update -y jq",
	},
	"Scoop": {
		"git":        "scoop update git",
		"docker":     "scoop update docker",
		"lazygit":    "scoop update lazygit",
		"lazydocker": "scoop update lazydocker",
		"htop":       "scoop update htop",
		"nvim":       "scoop update neovim",
		"tmux":       "scoop update tmux",
		"fzf":        "scoop update fzf",
		"ripgrep":    "scoop update ripgrep",
		"fd":         "scoop update fd",
		"bat":        "scoop update bat",
		"jq":         "scoop update jq",
	},
	"Chocolatey": {
		"git":        "choco upgrade git -y",
		"docker":     "choco upgrade docker-desktop -y",
		"lazygit":    "choco upgrade lazygit -y",
		"lazydocker": "choco upgrade lazydocker -y",
		"htop":       "choco upgrade htop -y",
		"nvim":       "choco upgrade neovim -y",
		"fzf":        "choco upgrade fzf -y",
		"ripgrep":    "choco upgrade ripgrep -y",
		"fd":         "choco upgrade fd -y",
		"bat":        "choco upgrade bat -y",
		"jq":         "choco upgrade jq -y",
	},
}

// GetUpdateCommand retrieves the update command for a specific tool using a specific method
// Returns empty string if method or tool is not found in the commands map
func GetUpdateCommand(method, tool string) string {
	return GetLifecycleCommand(GetLifecycleCommandType{
		method:                method,
		tool:                  tool,
		LifecycleCommandsType: PackageManagerUpdateCommands,
	})
}
